language: c

git:
    submodules: true

before_install:
    - docker build -t staticdeps-travis -f docker/Dockerfile-travis .

script:
    - mkdir -p ${PWD}/docker-artifacts
    - docker run --rm -v ${PWD}/docker-artifacts:/usr/src/staticdeps/_build staticdeps-travis

after_success:
    - ./travis/upload.sh
