language: c

matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required

git:
    submodules: false

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y -qq software-properties-common
    - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
    - sudo apt-get -qq update
    - sudo apt-get install -y -qq autopoint automake autoconf intltool libc6-dev-i386 libc6-dev yasm libglib2.0-bin libx11-dev perl wget g++-multilib zip bzip2 make libtool pkg-config cmake libglib2.0-dev libexpat-dev autogen automake1.11 automake1.9

script:
    - ./travis/build.sh

after_success:
    - ./travis/upload.sh

