FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get -qq update
RUN apt-get install -y -qq --allow-unauthenticated autopoint automake autoconf intltool libc6-dev yasm libglib2.0-bin perl wget g++-multilib zip bzip2 make libtool pkg-config cmake libglib2.0-dev libexpat-dev autogen clang
