FROM ubuntu:xenial

RUN apt-get -qq update
RUN apt-get install -y -qq apt-transport-https ca-certificates gnupg software-properties-common
RUN add-apt-repository "deb https://apt.kitware.com/ubuntu/ xenial main"
RUN apt-get -qq update
RUN apt-get install -y -qq --allow-unauthenticated autopoint automake autoconf intltool libc6-dev yasm libglib2.0-bin perl wget g++-multilib zip bzip2 make libtool pkg-config cmake libglib2.0-dev libexpat-dev autogen clang
