FROM ubuntu:trusty

RUN apt-get -qq update
RUN apt-get install -y -qq software-properties-common
RUN add-apt-repository ppa:george-edison55/cmake-3.x
RUN apt-get -qq update
RUN apt-get install -y -qq autopoint automake autoconf intltool libc6-dev-i386 libc6-dev yasm libglib2.0-bin perl wget g++-multilib zip bzip2 make libtool pkg-config cmake libglib2.0-dev libexpat-dev autogen texinfo

WORKDIR /usr/src/staticdeps
COPY ./src /usr/src/staticdeps/src
COPY ./prebuilt /usr/src/staticdeps/prebuilt
COPY ./tools /usr/src/staticdeps/tools
COPY ./travis /usr/src/staticdeps/travis
COPY ./libgtk-x86_64 /usr/src/staticdeps/libgtk-x86_64
ENV TRAVIS_OS_NAME=linux

CMD [ "bash", "travis/build.sh" ]
