FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC
RUN apt-get -qq update
RUN apt-get install -y -qq software-properties-common autopoint automake autoconf intltool libc6-dev yasm libglib2.0-bin perl wget zip bzip2 make libtool pkg-config cmake libglib2.0-dev libexpat-dev autogen gcc g++ clang libstdc++-9-dev bsdmainutils
