name: Build for Linux

on: [ push, pull_request ]

jobs:
  build:
    name: CI for Linux
    runs-on: ubuntu-latest
    container: ubuntu:16.04
    steps:
    - name: Install dependencies for Linux
      run: |
        apt-get -qq update
        apt-get install -y -qq apt-transport-https ca-certificates gnupg software-properties-common
        add-apt-repository "deb https://apt.kitware.com/ubuntu/ xenial main"
        apt-get -qq update
        apt-get install -y -qq --allow-unauthenticated autopoint automake autoconf intltool libc6-dev yasm libglib2.0-bin perl wget g++-multilib zip bzip2 make libtool pkg-config cmake libglib2.0-dev libexpat-dev autogen texinfo clang libkqueue-dev openssh-client rsync
    - name: Checkout for Linux
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build for Linux
      run: TRAVIS_OS_NAME=linux travis/build.sh
    - name: Upload for Linux
      env:
          gh_ed25519_key: ${{ secrets.GH_ENCRYPTED_ED25519_KEY }}
          gh_ed25519_iv: ${{ secrets.GH_ENCRYPTED_ED25519_IV }}
      run: TRAVIS_OS_NAME=linux travis/upload.sh
